import { randomBytes, createCipheriv, createDecipheriv } from "crypto";

// For AES-256-GCM, key must be exactly 32 bytes. The auth tag is always 16
// bytes for GCM (fixed by the algorithm).
const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;

/**
 * Get the secret key from environment variable. 
 * Must be a 32-byte string (or 64-char hex)
 */
function getSecretKey(): Buffer {
  const envKey = process.env.FULFILLMENT_SECRET_KEY;
  if (!envKey) {
    // Development fallback (DO NOT use in production)
    return Buffer.alloc(32, "dev-fallback-secret-key-32bytes!");
  }
  
  // Support hex encoded key if length is 64
  if (envKey.length === 64) {
    return Buffer.from(envKey, "hex");
  }
  
  // Or raw string padded/truncated to 32 bytes
  const buf = Buffer.alloc(32);
  buf.write(envKey, "utf8");
  return buf;
}

/**
 * Encrypt a plaintext string using AES-256-GCM
 * Returns formatted string: base64(iv):base64(auth_tag):base64(encrypted)
 */
export function encryptText(text: string): string {
  if (!text) return "";
  
  const key = getSecretKey();
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, "utf8", "base64");
  encrypted += cipher.final("base64");
  
  const authTag = cipher.getAuthTag().toString("base64");
  
  return `${iv.toString("base64")}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a ciphertext generated by `encryptText`
 */
export function decryptText(ciphertext: string): string {
  if (!ciphertext) return "";
  
  const parts = ciphertext.split(":");
  if (parts.length !== 3) {
    // Legacy plaintext support or corrupted data
    return ciphertext; 
  }
  
  const [ivBase64, authTagBase64, encryptedBase64] = parts;
  
  try {
    const key = getSecretKey();
    const iv = Buffer.from(ivBase64, "base64");
    const authTag = Buffer.from(authTagBase64, "base64");
    
    const decipher = createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedBase64, "base64", "utf8");
    decrypted += decipher.final("utf8");
    
    return decrypted;
  } catch (error) {
    console.error("Decryption failed:", error);
    return "[[ ERROR: DECRYPTION_FAILED ]]";
  }
}
