/**
 * Unit-level QA for admin password checking (src/lib/admin-auth.ts).
 *
 * Exercises the pure helper `checkPasswordAgainst` in-process: bcrypt mode,
 * legacy plain mode, malformed-hash fail-closed, and the 72-byte truncation
 * regression that the SHA-256 pre-hash is designed to prevent. No server or
 * DATABASE_URL required.
 *
 * Also verifies the wiring `checkAdminPassword` against the configured
 * ADMIN_PASSWORD (from .env.local / environment) when one is present.
 *
 *   npm run check:admin-pass
 */
import dotenv from "dotenv";
import { createHash } from "crypto";
import fs from "fs";
import os from "os";
import path from "path";
import bcrypt from "bcryptjs";

dotenv.config({ path: ".env.local" });

const ROUNDS = 4; // test-only cost — this checks correctness, not timing

const sha256hex = (s: string) => createHash("sha256").update(s, "utf8").digest("hex");

function assert(cond: boolean, msg: string) {
  if (!cond) throw new Error(`ASSERT FAILED: ${msg}`);
}

async function main() {
  // Loaded after dotenv so the module-level ADMIN_PASS binds to the
  // configured environment (dynamic import avoids top-level await in CJS).
  const { checkPasswordAgainst, checkAdminPassword } = await import("../src/lib/admin-auth");
  // ---- bcrypt mode ----
  const pw = "S3cure-Admin-Pass!2026";
  const hash = bcrypt.hashSync(sha256hex(pw), ROUNDS);
  assert(hash.startsWith("$2"), "bcrypt hash carries $2 prefix");

  assert(checkPasswordAgainst(hash, pw) === true, "bcrypt: correct password accepted");
  assert(checkPasswordAgainst(hash, "wrong-password") === false, "bcrypt: wrong password rejected");
  assert(checkPasswordAgainst(hash, "") === false, "bcrypt: empty input rejected");
  assert(checkPasswordAgainst(hash, pw + "extra") === false, "bcrypt: suffix must not match");

  // 72-byte truncation regression: both passwords share the first 72 bytes but
  // differ in the tail. Without the pre-hash, bcrypt would truncate both to the
  // same 72 bytes and wrongly accept. Pre-hash must make the tail significant.
  const longA = "X".repeat(72) + "A";
  const longB = "X".repeat(72) + "B";
  assert(bcrypt.truncates(longA) && bcrypt.truncates(longB), "precondition: inputs exceed 72 bytes");
  const hashLongA = bcrypt.hashSync(sha256hex(longA), ROUNDS);
  assert(checkPasswordAgainst(hashLongA, longA) === true, "bcrypt: long password accepted");
  assert(checkPasswordAgainst(hashLongA, longB) === false, "bcrypt: 72-byte truncation regression — differing tail must not match");

  // Malformed hash in env must fail closed, not throw.
  assert(checkPasswordAgainst("$2malformed-not-a-hash", pw) === false, "bcrypt: malformed hash fails closed");

  // ---- legacy plain mode (timing-safe fallback) ----
  const plain = "local-admin-dev";
  assert(checkPasswordAgainst(plain, plain) === true, "plain: exact match accepted");
  assert(checkPasswordAgainst(plain, "") === false, "plain: empty rejected");
  assert(checkPasswordAgainst(plain, plain + " ") === false, "plain: trailing space rejected");
  assert(checkPasswordAgainst(plain, plain.toUpperCase()) === false, "plain: case mismatch rejected");
  assert(checkPasswordAgainst(plain, "short") === false, "plain: length-different input rejected");

  // ---- wiring: checkAdminPassword delegates to configured ADMIN_PASSWORD ----
  if (process.env.ADMIN_PASSWORD) {
    const configured = process.env.ADMIN_PASSWORD;
    const isBcrypt = configured.startsWith("$2");
    assert(checkAdminPassword("") === false, "wiring: empty rejected");
    if (!isBcrypt) {
      assert(checkAdminPassword(configured) === true, "wiring: configured plain password accepted");
      assert(checkAdminPassword("definitely-not-it") === false, "wiring: wrong password rejected");
    } else {
      // bcrypt-wired env: verify with the pre-hash contract, without printing
      // the real password. If the hash was generated by hash-password.ts, the
      // input must be hashed the same way — so use checkPasswordAgainst with
      // the same stored value; correctness is proven by the pure tests above.
      console.log("  (configured ADMIN_PASSWORD is a bcrypt hash — wiring path is bcrypt mode)");
    }
  } else {
    console.log("  (no ADMIN_PASSWORD configured — skipping wiring check)");
  }

  // ---- Next env-loader round-trip regression ----
  // Next 16's loader interpolates "$VAR"-like tokens, so a RAW bcrypt hash in
  // .env.local would be mangled ($2b$10$... tokens stripped). The escaped form
  // (\$2b\$10\$...) must survive the loader and round-trip to the raw hash.
  // This is the exact failure mode caught live during e2e QA.
  {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "admin-pass-"));
    try {
      const escapedHash = hash.replace(/\$/g, "\\$");
      fs.writeFileSync(path.join(dir, ".env"), `ADMIN_PASSWORD="${escapedHash}"\n`);
      delete process.env.ADMIN_PASSWORD; // force @next/env to parse the temp value
      const { loadEnvConfig } = await import("@next/env");
      const { combinedEnv } = loadEnvConfig(dir, false);
      assert(
        combinedEnv.ADMIN_PASSWORD === hash,
        `next-env: escaped hash round-trips to raw hash (got len ${combinedEnv.ADMIN_PASSWORD?.length ?? 0})`,
      );
      assert(
        combinedEnv.ADMIN_PASSWORD?.startsWith("$2") === true,
        "next-env: round-tripped value is a bcrypt hash",
      );
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
      delete process.env.ADMIN_PASSWORD;
    }
  }

  console.log("admin-pass self-check OK");
}

main().catch((e) => {
  console.error("admin-pass self-check FAILED:", e);
  process.exit(1);
});
